#!/bin/bash

HOSTNAME=`hostname -s`
NODE_NUMBER=`cat -n ${HOSTFILE} | grep $HOSTNAME | awk '{print $1}'`

echo "[${HOSTNAME}] OMPI_COMM_WORLD_SIZE=${OMPI_COMM_WORLD_SIZE}"
echo "[${HOSTNAME}] OMPI_COMM_WORLD_RANK=${OMPI_COMM_WORLD_RANK}"
echo "[${HOSTNAME}] OMPI_COMM_WORLD_LOCAL_SIZE=${OMPI_COMM_WORLD_LOCAL_SIZE}"
echo "[${HOSTNAME}] OMPI_COMM_WORLD_LOCAL_RANK=${OMPI_COMM_WORLD_LOCAL_RANK}"
echo "[${HOSTNAME}] OMPI_COMM_WORLD_NODE_RANK=${OMPI_COMM_WORLD_NODE_RANK}"

export MACHINE_RANK=$((NODE_NUMBER-1))
echo "[${HOSTNAME}] MACHINE_RANK=$MACHINE_RANK"

NODE_CONFIG_FILE="${PATH_PREFIX}.${NODE_NUMBER}_${NUM_NODES}.yaml"

accelerate launch --config_file $NODE_CONFIG_FILE nlp_example.py
